language: R
sudo: false
cache:
  packages: true
warnings_are_errors: true
r_binary_packages:
  - testthat
  - httptest
  - knitr
r_github_packages:
  - r-lib/covr
after_success:
  - Rscript -e 'covr::codecov()'
