language: R
sudo: false
cache: packages
warnings_are_errors: true

r_binary_packages:
 - testthat
 - knitr

r_github_packages:
 - r-lib/covr

after_success:
 - Rscript -e 'library(covr); coveralls()'
