language: R
sudo: false
cache: packages
warnings_are_errors: true
r_binary_packages:
- testthat
- knitr
r_github_packages:
- r-lib/covr
after_success:
- Rscript -e 'library(covr); coveralls()'
env:
  matrix:
  - secure: J/Vyw1RQwTHi5Dqc/nUSgFyfO8SQ2741jdqASRmgDpvTTewn1gJqrX1gzEutqp4E4D/ysnQKj2qg60ZOin1U1RiAUQcvhvd1giJHLmHscxjO/E/kixd8mtYJPVpH6mTl67uq+nmxWeJ+iZceDdFnhpQmUMGzcuAZrsvCoRhPutsxJPSOyrHeeXLzfMNsTsv6GI0Kgy6YZCpxjvwyIJYNwbjXMC1aaPK6iEUSMY6qFwa08FIK87EG24MS+t36URwiMPrIs88DmQXbpIw1HV4h7JW0lv5xKPO2rq3KLc+0y6vqQC0miZK5PCphbz0zehyC02azBB9DtE3+BMXUehq25wCDPmXoXIKWaRB4G1+xYRSHbpw0PAE6zbIdwMQPiYa3SekFtRaIXaRwem6YiuZUdQT2H9BD3lmDJE+W0ZM0bYlDtSIwdJ212I8hnGHSzFPK9sPyQcStMOx1wGWAuZUzHjIEDdFaZduw1Aj2mpLangdrs0IJWm/LqR+HJw9zEDMLGijIgmQ3JG4573gR880TehRKD2Nkf9i9Rillcb0GQ68RnyXc+pELRxlNxTtSSlJRMxbriDspjcpUdunfNiFervYRJHSk8vS5cPHLHbk6xAaWg6EqQlg79Gjt45ry2gwzEbFZXnkRLrXhB9+ZIhXp4db/vrjiPaiRRQ6YYLgwcgI=
